### ISSUE TITLE
macOS Desktop application won't start

### ISSUE THREAD

**Issue by Merkwurdichliebe** [simonw/datasette.io#138]
Downloaded, unzipped and moved to /Applications. Loading screen shows downloading of packages to `~/.datasette-app', then stops and hangs with the spinning icon animation and the Loading... window open. Last lines show:
```
six>=1.5 in lib/python3.9/site-packages (from python-dateutil->sqlite-utils->datasette-app-support>=0.11.6) (1.16.0)
Took 627ms
```
Quitting and relaunching does the same thing except that everything shows "Requirement already satisfied".

macOS Monterey 12.6.2. `~/.datasette-app' folder size is 38.2mb.

**Comment by simonw** [comment]
This is fixed in the latest release - 0.2.3 - now available from https://datasette.io/desktop
